### PR TITLE
Allow specifying additional FSLeyes arguments

### PR DESCRIPTION
**Pull request by valosekj**
## Description

This PR adds the possibility to specify additional FSLeyes arguments:

- [x] [`-cm` (color map) and `dr` (min/max)]( https://github.com/spinalcordtoolbox/manual-correction/issues/9) - done in https://github.com/spinalcordtoolbox/manual-correction/commit/7a6aa3d4a511f96467c088078efbcb991d1ede3f
- [x] [open different orthoview](https://github.com/spinalcordtoolbox/manual-correction/issues/10) - done in https://github.com/spinalcordtoolbox/manual-correction/pull/13/commits/e648fffb1f07065e48423de18e4530fef76202d6
- [x] add examples to wiki - done in https://github.com/spinalcordtoolbox/manual-correction/wiki/Home/831ca7daa816710e4981e41a8be5c583efc95cbe

**NOTE**: since a second orthoview [cannot be opened from CLI](https://www.jiscmail.ac.uk/cgi-bin/wa-jisc.exe?A2=ind2301&F=5496681621512503&L=FSL&O=D&P=31427&X=3FB009402978E6EF53&Y=julien.cohenadad%40gmail.com), I proposed a [function](https://github.com/spinalcordtoolbox/manual-correction/blob/68d0f449679fe334808acc2b684dfef90ac3bc74/manual_correction.py#L225-L249) which creates a custom python script to configure individual orthoviews. Example result:

image

## How to test this PR

1. Clone:

```
git clone https://github.com/spinalcordtoolbox/manual-correction.git
cd manual-correction
git checkout jv/add_fsleyes_options
python3 -m venv venv
source venv/bin/activate
pip install -r requirements.txt
```

2. Download the [testing dataset](https://www.dropbox.com/s/adkgjqgxn2wj4iq/manual_correction_example_dataset.zip?dl=0).

3. Run:

```
python manual_correction.py -path-in ~/Downloads/manual_correction_example_dataset/data_processed -config ~/Downloads/manual_correction_example_dataset/files_to_correct.yml -viewer fsleyes -fsleyes-cm blue -fsleyes-dr 0,50 -fsleyes-second-orthoview
```

---

FIxes: https://github.com/spinalcordtoolbox/manual-correction/issues/9, https://github.com/spinalcordtoolbox/manual-correction/issues/10

### CODE REVIEW

**Review by sandrinebedard — CHANGES_REQUESTED** [review]
I've tested it out and 2 things I noticed:

1) When running the help command, I got this error, that I don't get on the main branch
~~~
(/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction) sabeda@DESKTOP-JQ8A4UV:/mnt/c/Users/sb199/manual-correction$ python manual_correction.py -h
Traceback (most recent call last):
  File "/mnt/c/Users/sb199/manual-correction/manual_correction.py", line 622, in <module>
    main()
  File "/mnt/c/Users/sb199/manual-correction/manual_correction.py", line 480, in main
    args = parser.parse_args()
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 1826, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 1859, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 2072, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 2012, in consume_optional
    take_action(action, args, option_string)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 1936, in take_action
    action(self, namespace, argument_values, option_string)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 1099, in __call__
    parser.print_help()
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 2560, in print_help
    self._print_message(self.format_help(), file)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 2544, in format_help
    return formatter.format_help()
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 283, in format_help
    help = self._root_section.format_help()
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 214, in format_help
    item_help = join([func(*args) for func, args in self.items])
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 214, in <listcomp>
    item_help = join([func(*args) for func, args in self.items])
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 533, in _format_action
    help_text = self._expand_help(action)
  File "/mnt/c/Users/sb199/spinalcordtoolbox/python/manual-correction/lib/python3.10/argparse.py", line 630, in _expand_help
    return self._get_help_string(action) % params
ValueError: unsupported format character 't' (0x74) at index 24
~~~
2) I get that the script crashed:
image
It opens the ortho views, but I don't see the toolbar and location panel. 

image

**Review by naga-karthik — APPROVED** [review]
lgtm and works on my end! I am able to modify colours, specify different range and view the images on both the views.
Maybe the orthoview issues are on Windows machines only?

**Comment by valosekj** [comment]
Thank you for testing Sandrine!


> ValueError: unsupported format character 't' (0x74) at index 24

Might this be an error caused by Windows or by the French localization of your laptop?

>    It opens the ortho views, but I don't see the toolbar and location panel.

Again, might it be caused by Windows? Or maybe by the FSLeyes version? You can check the version by:

```
fsleyes -V
```

I'm using FSLeyes 1.5.0.

**Comment by valosekj** [comment]
> 1. When running the help command, I got this error, that I don't get on the main branch
> 
> ```
> ...
> ValueError: unsupported format character 't' (0x74) at index 24
> ```

Okay, the `ValueError` was caused by the `%` character. Fixed in https://github.com/spinalcordtoolbox/manual-correction/pull/13/commits/e3d9cbcf777a44ba4cbcaba37786ca1d46083549. [Source](https://stackoverflow.com/a/64617467)

**Pull request merged**
