### PR TITLE
Add new function to track corrections

### PR DESCRIPTION
**Pull request by NathanMolinier**
## Description
This PR enables to track corrections when doing manual corrections (see https://github.com/spinalcordtoolbox/manual-correction/issues/49).

## Related issues
https://github.com/spinalcordtoolbox/manual-correction/issues/49

### CODE REVIEW

**Comment by valosekj** [comment]
Tested on `whole-spine` using:

```console
$ python manual_correction.py -path-img whole-spine -config whole-spine/config.yml -path-out test_folder
```

with the following initial `config.py`:
```YML
FILES_SEG:
- sub-amuAL_T1w.nii.gz
- sub-amuALT_T1w.nii.gz
```

After checking the first subject, the YML file has been correctly updated:
```YML
FILES_SEG:
# - sub-amuAL_T1w.nii.gz
- sub-amuALT_T1w.nii.gz
```

Now, If I run `manual_correction.py` again, the first subject with `#` is skipped.

---

However, the situation is a bit more tricky with `*` wildcard. Because, with `*`, the `glob.glob` command gets all the subjects including the subjects with starting `#`.

```YML
FILES_SEG:
# sub-amuAL_T1w.nii.gz
- sub-amu*.nii.gz
FILES_LABEL:
- sub-amu*.nii.gz
```

Possible solution: remove the subjects with `#` from the list returned by `glob.glob`.

**Comment by NathanMolinier** [comment]
The process is now different to effectively deal with all the cases:
- path list
- wildcard use

**Review by valosekj — COMMENTED** [review]
Thanks for the update @NathanMolinier! 

Tested on the `whole-spine` dataset using:

```console
$ python manual_correction.py -path-img whole-spine -config whole-spine/config.yml -path-out test_folder
```

with the following initial `config.yml`:

```yml
FILES_LABEL:
- sub-amuAL_T1w.nii.gz
- sub-amuALT_T1w.nii.gz
```

After correcting both subjects, the updated `config.yml` looks like this:

```yml
CORR_LABEL:
- sub-amuAL_T1w.nii.gz
- sub-amuALT_T1w.nii.gz
FILES_LABEL: []
```

Here, I have a suggestion -- since we are modifying the `config.yml` file, we could create its backup before we modify it. We can name it, for example, `config_backup.yml`. Why? To ensure that the original (non-modified) config file will not be lost.

Also, if I now try to run the `manual_correction.py` script again, I get an error: 

```console
$ python manual_correction.py -path-img whole-spine -config whole-spine/config.yml -path-out test_folder
Traceback (most recent call last):
  File "/Users/valosek/code/manual-correction/manual_correction.py", line 862, in <module>
    main()
  File "/Users/valosek/code/manual-correction/manual_correction.py", line 695, in main
    utils.check_files_exist(dict_yml, path_img, path_label, suffix_dict)
  File "/Users/valosek/code/manual-correction/utils.py", line 212, in check_files_exist
    if files is not None and '*' not in files[0]:
IndexError: list index out of range
```

The error is raised because the `FILES_LABEL` key does not contain any value. We should raise an error here, similar to this one: 
https://github.com/spinalcordtoolbox/manual-correction/blob/d05a456c3997d1098f2c099fd4388f3f13e2009a/manual_correction.py#L843-L844

**Comment by NathanMolinier** [comment]
I fixed two issues, it should work fine now !

Regarding the `config_backup.yml`, I'm not a huge fan:
- I don't see the point of creating a new file that will never be used and might confuse the user. 
- Moreover, with this changes, we are only adding information in the YAML file so nothing will be lost.
- It is also really simple to replace the prefix `CORR` with `FILES` to correct the same data again 
- The user can make is own copy before running the script

Lastly, should we create a backup file for every iteration of the script even with the same config file ? Should we overwrite it instead ? How could we check that the script was not runned before ?

**Review by valosekj — APPROVED** [review]
Tested in-person with @NathanMolinier and working fine --> meging.

**Pull request merged**
